### ISSUE TITLE
compute resource: what do we do if the identical job is queued again when the first instance is not yet complete?

### ISSUE THREAD

**Issue by magland** [flatironinstitute/hither#11]

**Comment by jsoules** [comment]
Upon reflection, I don't think there's a good solution to this that doesn't involve interacting with the job cache. Based on job cache settings, we may need to require rerunning the Job--it's probably not advisable, but it's an allowed configuration the user can do, and if they want to run a Job twice, we shouldn't give them unpredictable behavior based on whether the first run happened to have been complete or not before the second run got processed.

On the other hand, if they do want to cache the job, subsequent runs should be hitting the cache, and thus we can drop any second runs entirely.

Possible solution: start telling the job cache about jobs that exist but are in an in-progress or pre-complete status? If we use the same mechanism for complete and incomplete jobs, we'd be able to do away with the duplicate job-hashing functionality (efficiency_job_hash vs job_hash, with the former implemented but not yet used).
