### ISSUE TITLE
Rename Hither2 -> Hither, [SpikeForest] Hither -> Hither_SF

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/hither#12]
This package is being publicly released, it should have a more intuitive name, but we can't have a conflict with the earlier version already in SpikeForest.

**Comment by magland** [comment]
Note: within [spikeforest2](https://github.com/flatironinstitute/spikeforest2), we need to rename hither to hither_sf

**Comment by magland** [comment]
I will make the changes on spikeforest2
