### ISSUE TITLE
Set up autodeployment to PyPI via Travis

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/hither#13]
This is already set up for other laboratorybox projects, but needs to be added to this project when ready to release.

**Comment by magland** [comment]
I set this up and it is being deployed to here: https://pypi.org/project/hither/

I adjusted this to only deploy when we have a tagged commit on the "release" branch.

The tag should equal the version from the setup.py

**Comment by magland** [comment]
TODO: make sure that 0.1.4 has been deployed (in progress). If so, then things are probably working and we can close this issue.

**Comment by jsoules** [comment]
0.1.5 has been deployed; does this mean we're good on this?

**Comment by magland** [comment]
yes. closing.
