### ISSUE TITLE
syntax suggestion: consolidate decorators

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/hither#142]
Hey guys, I'm just poking around here. Seems really interesting and potentially useful for many of the projects I am working on. I like the use of decorators here. It seems like this project has a great minimally intrusive way to add dockerization functionality to a python project.

It may be a bit late in the project to make this sort of change, but I do have a syntax suggestion:
It looks like `hi.container` only makes sense after a `hi.function` decorator, and wouldn't make sense on its own. Because of this, I think it would be more intuitive if `container` and any other decorators that currently come after `hi.function` would instead be optional kwargs, e.g.

```python
@hi.function('integrate_bessel', '0.1.0',
             container='docker://jsoules/simplescipy:latest')
def integrate_bessel(v, a, b):
```
I would find that more intuitive. You could add this as an option while keeping the current way of doing it.

**Comment by magland** [comment]
Thanks @bendichter. I like your suggestion, and it should be straightforward to implement (and does not conflict with existing syntax). I am assigning myself to this, and I hope to have a PR for it relatively soon.

**Comment by magland** [comment]
@bendichter, if you have a chance, please take a look at the PR I just made to expand the syntax as you suggest.

**Comment by magland** [comment]
I am going to merge that PR as is for now since container is the most important and most common of the decorators.

I agree that this syntax should be made available for the other decorators as well. Should be straightforward to implement. I will keep this issue open and someone can implement it once it percolates up the priority list.
